// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtf6-ZvPARNhoZL-EXrUSiszxOFVh3yw0',
    appId: '1:421482704702:web:893483a8d838c51a10466f',
    messagingSenderId: '421482704702',
    projectId: 'student-mentoring-system-bd79a',
    authDomain: 'student-mentoring-system-bd79a.firebaseapp.com',
    storageBucket: 'student-mentoring-system-bd79a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgag9zjUpty0je-m-3lIc5HdYfCpkDo2E',
    appId: '1:421482704702:android:6afffbbb2ca6cc9310466f',
    messagingSenderId: '421482704702',
    projectId: 'student-mentoring-system-bd79a',
    storageBucket: 'student-mentoring-system-bd79a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTW2T8R_kOIrH4U54NQcBHEl0LAUXvVwA',
    appId: '1:421482704702:ios:a386fd6de00290e610466f',
    messagingSenderId: '421482704702',
    projectId: 'student-mentoring-system-bd79a',
    storageBucket: 'student-mentoring-system-bd79a.appspot.com',
    iosClientId: '421482704702-ld4vpbkblackqasm8fk97tedh5i42s3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentMentoringSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTW2T8R_kOIrH4U54NQcBHEl0LAUXvVwA',
    appId: '1:421482704702:ios:a386fd6de00290e610466f',
    messagingSenderId: '421482704702',
    projectId: 'student-mentoring-system-bd79a',
    storageBucket: 'student-mentoring-system-bd79a.appspot.com',
    iosClientId: '421482704702-ld4vpbkblackqasm8fk97tedh5i42s3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.studentMentoringSystem',
  );
}
